apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  DB_URL: $DB_URL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: my-app
    env: $ENV
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: $JAVA_OPTS
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_PASS